# Alfred production environment configuration
vault:
  path: "prod.db" # Database file path (relative to project root)
  # init_sql: "" # if not set, use default init sql file

logging:
  level: "DEBUG" # "INFO"

scheduler:
  interval_seconds: 60
  escalator_interval_seconds: 300

slack:
  channel: ""
