# Alfred production environment configuration
vault:
  path: "prod.db" # Database file path (relative to project root)
  # init_sql: "" # if not set, use default init sql file

logging:
  console_level: "INFO"
  file_level: "DEBUG"
  log_file: "alfred.log"

scheduler:
  interval_seconds: 60
  escalator_interval_seconds: 300

slack:
  channel: ""
  admin:
    - ""
