# Alfred 测试环境配置
vault:
  path: "postgresql+psycopg://alfred:alfred@localhost:5432/alfred_test"
  # path: "sqlite://./test.db"

logging:
  level: "DEBUG"

# better to set before tests?
# scheduler:
#   interval_seconds: 1
#   escalator_interval_seconds: 1

slack:
  channel: ""
  admin:
    - ""
