# Alfred production environment configuration
vault:
  path: "postgresql+psycopg://alfred:alfred@localhost:5432/alfred" # Database file path (relative to project root)
  # path: "sqlite://./prod.db"
  # init_sql: "" # if not set, use default init sql file

logging:
  console_level: "INFO"
  file_level: "DEBUG"
  log_file: "alfred.log"

scheduler:
  patrol_interval_seconds: 60
  engine_interval_seconds: 60

slack:
  channel: ""
  admin:
    - ""
